
print(1)
raise ValueError
print(2)

#1
# ValueError


